{% set name = "pyGPCCA" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 5e3b49279abc62d25133811daeee050715f995ff02042c46e2a2034331d090d1

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python  >=3.7
    - setuptools_scm
  run:
    - python  >=3.7
    - numpy >=1.15.0
    - scipy >=1.5.0
    - docrep >=0.3.1
    - mpi4py >=3.0.3
    - petsc >=3.13.0,!=3.14.0
    - slepc >=3.13.0
    - petsc4py >=3.13.0,!=3.14.0
    - slepc4py >=3.13.0

test:
  imports:
    - pygpcca

about:
  home: https://github.com/msmdev/pygpcca
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Generalized Perron Cluster Cluster Analysis
  description: |
    pyGPCCA employs Generalized Perron Cluster Cluster Analysis (G-PCCA) to coarse-grain reversible and in particular non-reversible Markov State Models.
    If you use pyGPCCA or parts of it, please cite Reuter et al. 2018 (https://doi.org/10.1021/acs.jctc.8b00079).
  doc_url: https://pygpcca.readthedocs.io/en/latest
  dev_url: https://github.com/msmdev/pygpcca

extra:
  recipe-maintainers:
    - msmdev
