{% set name = "pyGPCCA" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: a383636461698f6cda9a9e5678f9efb98ca2f8367b942221bc6d27f119f9be75

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python
    - numpy >=1.15.0
    - scipy >=1.5.0
    - docrep >=0.3.1
    - mpi4py >=3.0.3  # [not win]
    - msmpi >=10.1.1  # [win]
    - petsc >=3.13.0,!=3.14.0
    - slepc >=3.13.0
    - petsc4py >=3.13.0,!=3.14.0
    - slepc4py >=3.13.0

test:
  imports:
    - pygpcca
    - petsc4py
    - slepc4py
    - mpi4py

about:
  home: https://github.com/msmdev/pygpcca
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Generalized Perron Cluster Cluster Analysis
  description: |
    pyGPCCA employs Generalized Perron Cluster Cluster Analysis (G-PCCA) to coarse-grain reversible and in particular non-reversible Markov State Models.
    If you use pyGPCCA or parts of it, please cite Reuter et al. 2018 (https://doi.org/10.1021/acs.jctc.8b00079).
  doc_url: https://pygpcca.readthedocs.io/en/latest
  dev_url: https://github.com/msmdev/pygpcca

extra:
  recipe-maintainers:
    - msmdev
